version: '3.8'

services:
  portfolio:
    container_name: siliconecb-portfolio
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-5173}
      - NODE_ENV=production
    restart: unless-stopped
    network_mode: bridge

networks:
  default:
    external: true
    name: bridge
